service: travis-webhook

provider:
  name: aws
  runtime: nodejs6.10

functions:
  function:
    handler: handler.webhook
    events:
      - http:
          path: index
          method: post
          cors: true
    environment:
      WEBHOOK: /api/webhooks/${opt:api}